# Part A - Conceptual

## 1. Create Arrays & Indexing/Slicing

In [31]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [32]:
import numpy as np

In [33]:
# 1D array
arr1d = np.array([10, 20, 30, 40, 50])

# 2D array
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# 3D array
arr3d = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])


In [34]:
# Indexing & slicing
print(arr1d[2])        # single element
print(arr1d[1:4])      # slice

print(arr2d[1, :])     # 2nd row
print(arr2d[:, 2])     # 3rd column
print(arr2d[0:2, 1:3]) # subarray

print(arr3d[1, 1, 0])  # 2nd 2D array, 2nd row, 1st column

30
[20 30 40]
[4 5 6]
[3 6 9]
[[2 3]
 [5 6]]
7


## 2. Basic Operations (Vectorised, No Loops)

In [35]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [36]:
# Element-wise operations
print(a + b)   # addition
print(a - b)   # subtraction
print(a * b)   # multiplication

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [37]:
# Statistics
print(np.mean(a))       # mean
print(np.var(a))        # variance
print(np.std(a))        # standard deviation

2.0
0.6666666666666666
0.816496580927726


## 3. Broadcasting

In [38]:
# Add 1D array to 2D array
mat = np.array([[1, 2, 3],
                [4, 5, 6]])
vec = np.array([10, 20, 30])

In [39]:
print(mat + vec)   # row-wise addition

[[11 22 33]
 [14 25 36]]


In [40]:
# Multiply matrix by scalar
print(mat * 2)

[[ 2  4  6]
 [ 8 10 12]]


In [41]:
# Multiply matrix by vector (column-wise broadcasting)
col_vec = np.array([1, 2]).reshape(2, 1)
print(mat * col_vec)


[[ 1  2  3]
 [ 8 10 12]]


### Explanation of broadcasting:

Broadcasting in NumPy is a way of performing operations on arrays of different shapes by automatically expanding the smaller array to match the larger one. It works when dimensions are either equal or one of them is 1, allowing NumPy to replicate values along that axis. This makes element‑wise operations efficient without needing explicit loops.

NumPy automatically expands dimensions when shapes are compatible.

[2x3] + [3] -> [2x3] + [1x3] -> broadcast across rows.

[2x3] * scalar -> scalar is treated as [1x1], expanded to [2x3].

[2x3] * [2x1] -> broadcast column vector across columns.

## 4. Vectorised Operations

In [42]:
arr = np.array([-3, -1, 0, 2, 4])

In [43]:
# Square & cube
print(arr**2)
print(arr**3)


[ 9  1  0  4 16]
[-27  -1   0   8  64]


In [44]:
# Replace negatives with 0
arr_nonneg = np.where(arr < 0, 0, arr)
print(arr_nonneg)

[0 0 0 2 4]


In [45]:
# Normalize (scale between 0 and 1)
arr_norm = (arr - arr.min()) / (arr.max() - arr.min())
print(arr_norm)

[0.         0.28571429 0.42857143 0.71428571 1.        ]


## 5. Dataset Operations

In [46]:
data = np.array([[12, 7, 9],
                 [4, 15, 6],
                 [10, 2, 18]])

In [47]:
# Top 5 maximum values
top5 = np.sort(data.flatten())[-5:]
print(top5)

[ 9 10 12 15 18]


In [48]:
# Row-wise & column-wise sums
print(np.sum(data, axis=1))  # row sums
print(np.sum(data, axis=0))  # column sums

[28 25 30]
[26 24 33]


In [49]:
# Indices of values greater than threshold
threshold = 10
indices = np.argwhere(data > threshold)
print(indices)

[[0 0]
 [1 1]
 [2 2]]


# Part B :- Stretch Problem

## 1. Matrix Operations with NumPy

In [50]:
import numpy as np

In [55]:
# Define matrices
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])


In [56]:
# Matrix multiplication
C = np.dot(A, B)   # or A @ B
print("Matrix Multiplication:\n", C)

Matrix Multiplication:
 [[19 22]
 [43 50]]


In [57]:
# Transpose
print("Transpose of A:\n", A.T)

Transpose of A:
 [[1 3]
 [2 4]]


In [58]:
# Determinant
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

Determinant of A: -2.0000000000000004


## 2. Solve a System of Linear Equations

### 2X + Y = 5
### X - Y = 1

In [59]:
# Coefficient matrix
coeff = np.array([[2, 1],
                  [1, -1]])


In [64]:
# Constants
const = np.array([5, 1])

In [65]:
# Solve Ax = b
solution = np.linalg.solve(coeff, const)
print("Solution (x, y):", solution)

Solution (x, y): [2. 1.]


## 3. Performance Comparison

In [68]:
import time

In [69]:
# Large array
arr = np.arange(1_000_000)

In [70]:
# Python loop sum
start = time.time()
s = 0
for val in arr:
    s += val
end = time.time()
print("Loop sum:", s, "Time:", end - start)


Loop sum: 499999500000 Time: 0.09996223449707031


In [71]:
# NumPy sum
start = time.time()
s_np = np.sum(arr)
end = time.time()
print("NumPy sum:", s_np, "Time:", end - start)

NumPy sum: 499999500000 Time: 0.004462003707885742


The time difference between summing a large array with a Python loop versus using NumPy is significant because of how the computations are executed under the hood:

- Python loops run in the interpreter, processing one element at a time. Each iteration involves overhead (loop control, variable updates, type checks), which makes them slow for millions of elements.

- NumPy operations are vectorised: they delegate the heavy lifting to optimized C and Fortran libraries (like BLAS/LAPACK). These libraries operate directly on contiguous blocks of memory, using low-level machine instructions and sometimes parallelization.

As a result, NumPy avoids Python’s per‑element overhead and executes the entire operation in compiled code, which is orders of magnitude faster.